### ISSUE TITLE
ProtobufGeneratorGRPC not working

### ISSUE THREAD

**Issue by paulviks0x30** [halotron/ProtobufGenerator#10]
Hello,
I just install this exelent extension. When i type ProrobufGenerator in Custom Tool box extension just work an expected, but when I type ProrobufGeneratorGRPC after save changes in proto file its nothin happen. 
All nuget packages is installed on project and protoc is installed in global enviroment.
Best Regards,
Paul

**Comment by halotron** [comment]
The current build on marketplace is not updated to what is currently on github. I might be able to fix it this week or weekend.

**Comment by halotron** [comment]
there is a new version now in https://marketplace.visualstudio.com/items?itemName=jonasjakobsson.ProtobufGeneratorvisualstudio
