### ISSUE TITLE
Feature Request: Support specifying input arguments 

### ISSUE THREAD

**Issue by pme-abvaden** [halotron/ProtobufGenerator#11]
Would you be open to adding support specifying arguments when calling protoc? 

This would allow us to specify the root import path and other plugins to be run on file save.
I would be happy to submit a pull request if you are open to this feature.

I think things would also address issue
https://github.com/halotron/ProtobufGenerator/issues/5

**Comment by pme-abvaden** [comment]
What if we were to add a recognized comment on the .proto file and read the .proto file before passing it to protoc 

An example file could be something like

// ProtobufGenerator-Arg:proto_pth:IMPORT_PATH

import message_lib/MyMessage;

// This message uses a message type that is imported the shared message_lib/MyMessage file
message ABC {
   MyMessage Message = 1;
   uint32 Counter = 2;
}

**Comment by halotron** [comment]
That seems like a neat solution. Much better than the one I thought about. I can´t think of any reason not to accept such a PR, provided it is easily mergeable, stays to the point, and so on.

**Comment by pme-abvaden** [comment]
Awesome! 
I will work on something tonight!

**Comment by pme-abvaden** [comment]
I've got a working solution for specifying arbitrary arguments.

When working with the code though it seems like my need in particular and the need of issue #5 could be solved with just specifying extra proto path arguments. I think it might be a little more straight forward if instead of extending a way to specify arbitrary arguments we just allowed for the inclusion of extra proto_path options.

Also when looking through the available arguments for protoc it looks like modifying most of those arguments would at best have no effect on results of the plugin (or at worst break it's functionality i.e. writing the output to path that is not expected by the plugin).

You can see the changes here.
https://github.com/pme-abvaden/ProtobufGenerator/commit/339abf64045bb417a4b23aa2f3716ee63c73af22

If you think the plugin might be better served by just allowing for the use of extra proto_path options, I can clean up that tomorrow morning.

Here is a sample of the new file that you can use with the plugin
```
/// ProtobufGenerator-Arg:proto_path:../packages/Google.Protobuf.Tools.3.6.1/tools/
/// ProtobufGenerator-Arg:proto_path:../OtherLibrary/

syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "SharedProtos.proto";

package PME.MyCustomNamespace;

message TestMessage {
  bytes Data = 1;
  PME.MyCustomNamespace.One Test = 2;
  google.protobuf.Timestamp TimeStamp = 3;
}
```

**Comment by halotron** [comment]
It works! Good job.
I think it might be ok to allow ANY kind of parameters to protoc, but for now just allowing proto_path I think is enough. 
Allowing any parameters might as you say produce a file in the "wrong" place. But if the user have the knowledge of what parameters to use in the comment, then he probably also knows of its effects as well. Like having to add a file manually to the project.

**Comment by pme-abvaden** [comment]
Awesome, I appreciate the opportunity to work with you on this tool. I it has really been helpful to  me and my organization, with these changes we can clean up our code base a bit!

I have added a short section to the Readme about the argument feature and submitted a pull request.

**Comment by halotron** [comment]
Thanks! I will do the merge before friday. Too busy right now.

**Comment by halotron** [comment]
1.3 is in the marketplace now
